### ISSUE TITLE
Structure of collections data

### ISSUE THREAD

**Issue by despens** [webrecorder/public-web-archives#1]
Currently, data for collections within an archive is structure with the URL part of the collection as the key and a description as the value:

```yaml
collections:
    legislatives_france_2012: 'Elections Legislatives France 2012'
    presidentielles_france_2012: 'Elections Presidentielles France 2012'
    haeu: 'European Institutions – OP and HAEU'
    cern: 'European Organization for Nuclear Research (Switzerland) - CERN'
    nli: 'National Library of Ireland - NLI'
    nrs: 'National Records of Scotland'
    proni: 'Public Record Office of Northern Ireland - PRONI'
    tna: 'The National Archives - TNA'
```

This is too limiting for adding further info about a collection in the future, should rather be structured like:
