### ISSUE TITLE
Use more advanced YAML features?

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/public-web-archives#12]
There are a few advanced YAML features that could help avoid manual work for the user, though may be more confusing on first glance.

- References and node anchors (https://en.wikipedia.org/wiki/YAML#Advanced_components) can be used to insert the default replay and query suffixes:

For example, the default section could be:
```
api_defaults:
    default_wayback: &default_wayback
        calendar_suffix: &default_calendar_suffix '*/'

        replay_suffix: &default_replay_suffix
            raw: '{timestamp}id_/{url}'
            rewritten: '{timestamp}/{url}'

    imf_replay_suffix: &imf_replay
        raw: 'raw/{url}'
        rewritten: '{timestamp}/{url}'
```

And then could be used in this way:
```
# Using Default Wayback suffixes
    wayback:
        <<: *default_wayback
        prefix: 'http://wb.example.com/prefix/path'

# Using Default Wayback + Override Replay Suffix
    wayback:
        <<: *default_wayback
        prefix: 'http://wb.example.com/prefix/path'
        replay_suffix: *imf_replay
```

* Multiple documents in one file using the `---` separator.

This could allow both one archive per file, and also combining all the documents into a single file using the `---` separator?
