### ISSUE TITLE
Can further information on an archive improve querying and aggregation?

### ISSUE THREAD

**Issue by despens** [webrecorder/public-web-archives#4]
How about this?

```yaml
captures:
  domains:
    - .stanford.edu
    - facebook.com
  dateranges:
    from: 1994-01-01
    to: 2001-12-24
```
`to` key optional!

Could be a sub structure to whole web archives or collections.
