### ISSUE TITLE
Archive diverting from standard parameters needs to declare everything instead of just deviation from standard

### ISSUE THREAD

**Issue by despens** [webrecorder/public-web-archives#5]
The key `api_defaults` holds standard URL constructors for wayback-driven archives:

```yaml
api_defaults:
    wayback:
        replay_suffix:
            raw: '{timestamp}id_/{url}'
            default: '{timestamp}/{url}'

    calendar_suffix: '*/'
```

Currently, if an archive is accessible differently from the defaults, it has to declare the whole sub-structure:

```yaml
# override, no 'raw' available
replay_suffix:
    default: '{timestamp}/{url}'
```

This is weird since the actual change from the defauls is the missing `raw` key, but the declaration contains actually the oposite key, which is not different from the defaults.
