### ISSUE TITLE
Default configuration key names

### ISSUE THREAD

**Issue by despens** [webrecorder/public-web-archives#6]
Currently, the default configuration uses the key name `default` for different things:

```yaml
# default properties added to api block, if field unset
# eg. 'replay_suffix' only added if no replay_suffix present in definition block
api_defaults:
    wayback:
        replay_suffix:
            raw: '{timestamp}id_/{url}'
            default: '{timestamp}/{url}'
```
